### ISSUE TITLE
cifar dataset

### ISSUE THREAD

**Issue by Haoran-P** [LeapLabTHU/L2W-DEN#2]
May I ask for the code and hyperparameters of CIFAR datasets.
Thanks a lot.

**Comment by yizenghan** [comment]
Please refer to our reponse at https://github.com/LeapLabTHU/L2W-DEN/issues/1#issuecomment-1316568899

**Comment by Haoran-P** [comment]
Hi, thank you for your quick response.
the response#1 mentioned:
python tools/main_cifar.py
which is not exist 
Could you please provide this code, thanks a lot.

**Comment by yizenghan** [comment]
Hi, we will polish and provide the Cifar code ASAP. Actually, the only difference to the ImageNet code is the dataloaders and DDP training.
