### ISSUE TITLE
Missing main_cifar.py

### ISSUE THREAD

**Issue by metodj** [LeapLabTHU/L2W-DEN#3]
Hey,

thanks a lot for the nice codebase. 

I wanted to rerun some of your CIFAR experiments, however, I noticed that the `main_cifar.py` file you are mentioning in [this thread](https://github.com/LeapLabTHU/L2W-DEN/issues/1) is missing. Could you upload the file? 

Thanks in advance!

**Comment by yifanpu001** [comment]
Hi, we have uploaded the cifar file ```main_cifar_DDP.py``` to the ```./tools/``` directory. The only difference between it and the imagenet file is the dataloader. We have also added the training script to the ```README.md``` file.
